spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/CareConnect}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:amit7280}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
